package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User>  users= generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    //La fonction getUsers() retourne la liste d'utilisateurs users
    public List<User> getUsers() {
        // TODO: A modifier
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    //La fonction generateRandomUser() va ajouter un utilisateur généré par la fonction User.random
    //de la classe User et l'ajouter à la liste d'utilisateurs users.
    public void generateRandomUser() {
        // TODO: A modifier
        users.add(User.random());
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    //La fonction deleteUser va supprimer un utilisateur (de type User) passé en paramètre de la
    //liste d'utilisateurs users grace à la fonction
    public void deleteUser(User user) {
        // TODO: A modifier
        users.remove(user);
    }
}
